# Generated by Django 2.2.13 on 2020-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200725_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.SlugField(max_length=200),
        ),
    ]
